name: Generate ASCII artwork
on: push 
jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout Repo
          uses: actions/checkout@v4 

        # - name: welcome messgae
        #   run: |
        #     echo "my first github acions job"
        #     ls -ltra
        #     cat README.md
        - name: install Cowsay program
          run: sudo apt-get install cowsay -y  
            
        - name: Execute ASCII CMD
          run: cowsay -f dragon "Run for cover i ama dragon...">>dragon.txt
        - name: Test file Exists
          run: grep -i "dragon" dragon.txt
        - name: Read file
          run: cat dragon.txt
        - name: list Repo files
          run: ls ltra
        # - name: list file
        #   run: ls
            
        # - name: read file
        #   run: cat README.md